name: Test Jaid/action-sync-node-meta
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'action-sync-node-meta')"
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.0.0
      - uses: jaid/action-sync-node-meta@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}