name: Test Jaid/action-uptodater
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'action-uptodater')"
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.0.0
      - name: npm install
        uses: jaid/action-npm-install@master
      - name: Uptodater
        uses: jaid/action-uptodater@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fix: "true"
          approve: "true"