name: Validate and autofix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.2.0
      - name: npm install
        uses: jaid/action-npm-install@master
      - name: Jest
      - uses: jaid/action-jest@master
      - name: Uptodater
        uses: jaid/action-uptodater@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          approve: "true"
